export DOORDASH_API_KEY="your_doordash_api_key"
export UBER_API_KEY="your_uber_api_key"
export EXPEDIA_API_KEY="your_expedia_api_key"
export PLAID_CLIENT_ID="your_plaid_client_id"
export PLAID_SECRET="your_plaid_secret"
